### PR TITLE
Refactor some duplicated code

### PR DESCRIPTION
**Pull request by gluke77**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/128)

### CODE REVIEW

**Comment by nebril** [comment]
:lgtm: nice job!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/128#-:-KXzQdr9c-tnFfCjiwCe:bxpgx20)*

**Comment by pigmej** [comment]
shouldn't we adjust recently merged secrets to the same? @gluke77 could you rebase and apply it also there?

**Comment by gluke77** [comment]
@pigmej sure, will do

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/128#-:-KYDObjArAMmdPd8dmSn:bnfp4nl)*

**Pull request merged**
