### PR TITLE
Services and extended example added to e2e

### PR DESCRIPTION
**Pull request by dshulyak**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/204)

### CODE REVIEW

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/example_runner.go, line 79 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204#-KdkZjmAFer4Ym9HnLSv:-KdkZjmAFer4Ym9HnLSw:b1adtuj) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/b994daef4ac01b43b59e90df49942a8c8e2ac430/e2e/example_runner.go#L79)):*
> ```Go
> 	encodedData, err := json.Marshal(ust)
> 	Expect(err).NotTo(HaveOccurred())
> 	utils.Logf("Found resource with name %v and kind %v\n", ust.GetName(), ust.GetKind())
> ```

Maybe Logf should add newline by default? I would assume this when using logging function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204#-:-KdkcvazpECrD6rktWNf:bnfp4nl)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/example_runner.go, line 79 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204#-KdkZjmAFer4Ym9HnLSv:-Kdwf6Ce0uQ4L4KORs3q:b-kyoy1i) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/b994daef4ac01b43b59e90df49942a8c8e2ac430/e2e/example_runner.go#L79)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

Maybe Logf should add newline by default? I would assume this when using logging function
</blockquote></details>

+1 for that idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/example_runner.go, line 79 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204#-KdkZjmAFer4Ym9HnLSv:-KdykFwJtH4tchvV9QBD:bvfyu0h) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/b994daef4ac01b43b59e90df49942a8c8e2ac430/e2e/example_runner.go#L79)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

+1 for that idea.
</blockquote></details>

Maybe it should check if last char is `\n` and if not then it should add it?
Better would be to have `\n` added always by Logf and removed from all log format strings...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/client/resdef.go, line 47 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204#-Kdz9ycdQiMW9jEgcxhY:-Kdz9ycdQiMW9jEgcxhZ:bysy45w) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/b994daef4ac01b43b59e90df49942a8c8e2ac430/pkg/client/resdef.go#L47)):*
> ```Go
> 	ReplicaSet            *v1beta1.ReplicaSet       `json:"replicaset,omitempty"`
> 	StatefulSet           *appsbeta1.StatefulSet    `json:"statefulset,omitempty"`
> 	ServiceAccount        *v1.ServiceAccount        `json:"serviceaccount,omitempty"`
> ```

@dshulyak can we have this as separate PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204)*

**Comment by pigmej** [comment]
:lgtm: let's resolve newline in Logf in separate issue/pr :) 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/204#-:-KdzLxj_PMN9CNIH2lC4:byecdue)*

**Pull request merged**
