### PR TITLE
Support for secrets

### LINKED ISSUE #110: Secrets support
Support for Secrets object

### PR DESCRIPTION
**Pull request by pigmej**
closes #110 

It's pretty much the same code as #107 just changed `ConfigMap` to `Secret` etc. (including @nebril  test stuff)

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/114)

### CODE REVIEW

**Comment by nebril** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/114#-:-KXeH8oRFWl5xs7jCu2R:bnfp4nl)*

**Comment by pigmej** [comment]
@nebril rebased!

**Comment by nebril** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/114#-:-KXf64SzH7XWos3Wp-JY:bnfp4nl)*

**Comment by gluke77** [comment]
:lgtm:

---

Reviewed 5 of 14 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/114#-:-KXzHB585Bz1wybzY8kF:bnfp4nl)*

**Pull request merged**
