### PR TITLE
Refactoring of the AppController for the flows

### PR DESCRIPTION
**Pull request by istalker2**
* Defines interfaces for dependency graph and resource scheduler
* Passes those interfaces to resource template classes so that scheduler could be
   used as part or resource template deployment. Interfaces make it possible to avoid
   circular dependencies between resources and scheduler packages
* Modifies dependency graph construction algorithm so that resource factories are
   created in top-to-bottom order so that it possible to pass parameters and other context
   information along the graph. Also it should become possible to extract flow subgraph
   from the dependency graph
* Refactors resource template classes so that it will become possible to get wrapped
   resource name from its ResourceDefinition
* Updates unit tests for the changes made
* Replaces custom resource definitions and dependencies mock clients with standard
   Fake-based clients

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/221)

### CODE REVIEW

**Comment by jellonek** [comment]
Only one nit. Rest things will be covered in https://github.com/Mirantis/k8s-AppController/issues/217

---

Reviewed 43 of 43 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/scheduler/scheduler.go, line 293 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/221#-Kfq57cVepJ1gzK_wF5v:-Kfq57cWQ-XZltOLPvxQ:b841ciq) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7517762803e26677f5cac3f92243a2de360d61fb/pkg/scheduler/scheduler.go#L293)):*
> ```Go
> }
> 
> // Create starts the deployment of a DependencyGraph
> ```

Func name changed but docstring points to old name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/221#-:-Kfq5MoKM81qx6aEcYZK:bkqpi1j)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 43 of 43 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/221#-:-KfqKjfvOAh0w2zEYkqP:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/221#-:-KfqbONP3R9AAcD5qB1T:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/221#-:-KfqefBwHOYCrLzCoAFq:bnfp4nl)*

**Pull request merged**
