### PR TITLE
Add e2e test to verify that service status checking works correctly

### PR DESCRIPTION
**Pull request by dshulyak**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/190)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/basic_test.go, line 203 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/190#-Kbt2t89wBow6zeJIHUq:-Kbt2t89wBow6zeJIHUr:b-31y5h1) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/0c0ed2f9f229c5901691e22e9bc12f5e9d4acf95/e2e/basic_test.go#L203)):*
> ```Go
> 		"ac-run",
> 		"-l",
> 		"ns:"+g.ns,
> ```

Any specific reason for that? AC should work automaticaly if spawned in given namespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/190)*

**Comment by dshulyak** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/basic_test.go, line 203 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/190#-Kbt2t89wBow6zeJIHUq:-KbxsgqQ_tJtUgziRyVc:bj2c922) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/0c0ed2f9f229c5901691e22e9bc12f5e9d4acf95/e2e/basic_test.go#L203)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Any specific reason for that? AC should work automaticaly if spawned in given namespace.
</blockquote></details>

it was this way, i will remove it if there will be other issues with this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/190)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/190#-:-KbyHcc2sCLaMMkh1Xqo:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/190#-:-Kbyg_V3NPPtSLkFHstg:bnfp4nl)*

**Pull request merged**
