### PR TITLE
Updated roadmap in readme

### PR DESCRIPTION
**Pull request by pigmej**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/215)

### CODE REVIEW

**Comment by idvoretskyi** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/215#-:-Kf6c-kyT2UVidcEfcI_:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/215#-:-Kf6cPUXwcreY72G1YhJ:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/215#-:-Kf6dO6tkkH4cVGSLKKt:bnfp4nl)*

**Comment by istalker2** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/215#-:-Kf7Uju_whuEBv6yJfjk:bnfp4nl)*

**Pull request merged**
