### PR TITLE
Move golang code to pkg directory

### PR DESCRIPTION
**Pull request by dshulyak**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/161)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 97 of 97 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/161#-:-KZfzREBN8x213fSnuRp:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 97 of 97 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/161#-:-KZzhR27sdFnuH6STyK2:bnfp4nl)*

**Comment by nebril** [comment]
I think `make test` could be improved in this PR to just run tests from `pkg` and `cmd` directories.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/161#-:-KZzhX83oavVcTVDSd5d:b2ewmeq)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: 61 of 62 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/161#-:-K_3xOHmsffOkxOk2VRt:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/161#-:-K_4yX3i3Xw2gyVgRshN:bnfp4nl)*

**Pull request merged**
