### PR TITLE
Use kubeadm on CI and make it work on kube 1.6

### PR DESCRIPTION
**Pull request by dshulyak**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/225)

### CODE REVIEW

**Comment by istalker2** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUSOHRehnVhgwtsVD:-KflUSOHRehnVhgwtsVE:b29o4f3) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/.travis.yml#L9)):*
> ```YAML
>   - 1.7
> env:
>   - WORKING=$HOME/kube1.5 K8S_VERSION=v1.6 PUBLISH=1
> ```

Why does kube1.5 go with K8S_VERSION 1.6? Isn't 1.6 supposed to be another, 3rd env?

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUqUB8Oo4Aj061hRm:-KflUqUCX2aMjW-uRd_x:b-91nc7h) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/95913683696f7530d2565d7f155acbe76a724ba0/.travis.yml#L17)):*
> ```YAML
>     - go: 1.7
>       env: WORKING=$HOME/kube1.4 K8S_TAG=v1.4.9
> cache:
> ```

Why did you delete these lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225)*

**Comment by jellonek** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 14 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflWuziZRYn3JyX1SKV:-KflWuziZRYn3JyX1SKW:bfgzc1a) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/.travis.yml#L14)):*
> ```YAML
>   exclude:
>     - go: 1.6
>       env: WORKING=$HOME/kube1.5 K8S_TAG=v1.6 PUBLISH=1
> ```

Same question as Stan's above.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUqUB8Oo4Aj061hRm:-KflWRl6IjbQ3OCCmk3_:bdyy1h4) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/95913683696f7530d2565d7f155acbe76a724ba0/.travis.yml#L17)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

Why did you delete these lines?
</blockquote></details>

Whole patch is about removal old dind which was using these dirs in flavor of kubeadm-dind-cluster which uses prebuild images instead.

---

*[e2e/utils/utils.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUcGAEjtsEYFWoezM:-KflUcGAEjtsEYFWoezN:b-mjgvv3) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/e2e/utils/utils.go#L55)):*
> ```Go
> // AddServiceAccountToAdmins will add system:serviceaccounts to cluster-admin ClusterRole
> func AddServiceAccountToAdmins(c kubernetes.Interface) {
> 	if strings.Contains(TestContext.Version, "1.6") {
> ```

What about future versions?

---

*[e2e/utils/utils.go, line 73 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflVCocTyuB0yVB04oY:-KflVCocTyuB0yVB04oZ:b-ivi815) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/e2e/utils/utils.go#L73)):*
> ```Go
> 	}
> 	_, err := c.Rbac().ClusterRoleBindings().Create(roleBinding)
> 	Expect(err).NotTo(HaveOccurred(), "Wasnt able to create role binding for serviceaccounts")
> ```

wasn't

---

*[e2e/utils/utils.go, line 78 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflVVF0utX2PgyedZtL:-KflVVF0utX2PgyedZtM:b69pjkc) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/e2e/utils/utils.go#L78)):*
> ```Go
> func RemoveServiceAccountFromAdmins(c kubernetes.Interface) {
> 	err := c.Rbac().ClusterRoleBindings().Delete(rbacServiceAccountAdmin, nil)
> 	Expect(err).NotTo(HaveOccurred(), "Failed to remove serviceaccount from admin group")
> ```

Hmmm... Adding is for other than 1.6 versions, but removal is for all - this seems to be wrong.
I only want to ensure there that this is correct.

---

*[manifests/auth.yaml, line 11 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflVlaOiN-b9RN30nXX:-KflVlaOiN-b9RN30nXY:b-ks66qm) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/manifests/auth.yaml#L11)):*
> ```YAML
>   kind: ClusterRole
>   name: cluster-admin
>   apiGroup: rbac.authorization.k8s.io
> ```

Missing eol at eof.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUSOHRehnVhgwtsVD:-KflXHF_hqpqIdcgdynu:bib7eov) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/.travis.yml#L9)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

Why does kube1.5 go with K8S_VERSION 1.6? Isn't 1.6 supposed to be another, 3rd env?
</blockquote></details>

Probably typo :)  We should have 3 envs there for now, then we can think how to get rid of 1.4

---

*[e2e/utils/utils.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUcGAEjtsEYFWoezM:-KflXaLQRT3md3ZxwAVa:b-vwna9f) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/e2e/utils/utils.go#L55)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

What about future versions?
</blockquote></details>

Couldn't we do some version compare there instead? And just start from 1.6.0?

---

*[scripts/import.sh, line 12 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflXrvgfpMnuy9h-5Ir:-KflXrvhsMyZ8JEPPAr2:bkc99kj) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/scripts/import.sh#L12)):*
> ```Shell
> NUM_NODES=${NUM_NODES:-2}
> TMP_IMAGE_PATH=${TMP_IMAGE_PATH:-/tmp/image.tar}
> MASTER_NAME=${MASTER_NAME="kube-master"}
> ```

I like that they're back :D:D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225)*

**Comment by dshulyak** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUSOHRehnVhgwtsVD:-Kflke3Imq-TmA9l1mpL:bmnn45n) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/.travis.yml#L9)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Probably typo :)  We should have 3 envs there for now, then we can think how to get rid of 1.4
</blockquote></details>

yeah WORKING will be removed, i was in a rush a bit :)

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUqUB8Oo4Aj061hRm:-KflkwzaFUbbZ82gWbw2:b-x4rwj3) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/95913683696f7530d2565d7f155acbe76a724ba0/.travis.yml#L17)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Whole patch is about removal old dind which was using these dirs in flavor of kubeadm-dind-cluster which uses prebuild images instead.
</blockquote></details>

yes, they are not needed anymore

---

*[e2e/utils/utils.go, line 78 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflVVF0utX2PgyedZtL:-Kfll2OGznC5r-Qj6VUM:b-k73z76) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/e2e/utils/utils.go#L78)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... Adding is for other than 1.6 versions, but removal is for all - this seems to be wrong.
I only want to ensure there that this is correct.
</blockquote></details>

thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225)*

**Comment by jellonek** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[Makefile, line 44 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KfpMeVyKxIpIahBQAW3:-KfpMeVyKxIpIahBQAW4:bsv2ne9) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/26e604b6fba72e352e405ce39c4c151877a3290b/Makefile#L44)):*
> ```Makefile
> clean-k8s:
> 	./kubeadm-dind-cluster/fixed/dind-cluster-$(K8S_VERSION).sh down
> 	./kubeadm-dind-cluster/fixed/dind-cluster-$(K8S_VERSION).sh clean
> ```

At the beginning of `clean` `down` is called, so there is no reason to have the both there. Second one should be enough.

---

*[e2e/utils/utils.go, line 95 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KfpKxrGjbLMHahxbxB1:-KfpKxrGjbLMHahxbxB2:b-210htb) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/26e604b6fba72e352e405ce39c4c151877a3290b/e2e/utils/utils.go#L95)):*
> ```Go
> }
> 
> func SanitizedVersion() float64 {
> ```

Float? What about subversions?
Maybe better would be to use https://github.com/hashicorp/go-version ?
I have no strong opinion on this, as we clearly have now version based on vX.Y schema.

---

*[manifests/auth.yaml, line 11 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflVlaOiN-b9RN30nXX:-KfpLrLTD3HEGY2XQ8EW:b-xtehfh) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/manifests/auth.yaml#L11)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Missing eol at eof.
</blockquote></details>

Still missing eol.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[e2e/utils/utils.go, line 95 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KfpKxrGjbLMHahxbxB1:-KfpNFS5ib2vLb3qSP0-:b-dwse3p) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/26e604b6fba72e352e405ce39c4c151877a3290b/e2e/utils/utils.go#L95)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Float? What about subversions?
Maybe better would be to use https://github.com/hashicorp/go-version ?
I have no strong opinion on this, as we clearly have now version based on vX.Y schema.
</blockquote></details>

Ough, `go-version` has mozilla license, so this could be tricky :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KflUSOHRehnVhgwtsVD:-KfpNW57wv4ly_EqUWBR:btu62n7) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/60fbac6cf6f82024a5ed47f972e41cfcc2765635/.travis.yml#L9)):*
<details><summary><i>Previously, dshulyak (Dmitry Shulyak) wrote…</i></summary><blockquote>

yeah WORKING will be removed, i was in a rush a bit :)
</blockquote></details>

Have we actually checked if AC compiled with 1.6 will work in 1.5? (afair deployment API changed, isn't it?)

---

*[Makefile, line 44 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-KfpMeVyKxIpIahBQAW3:-KfpNh7R0a9qgRd4UCoa:b-7c1jgl) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/26e604b6fba72e352e405ce39c4c151877a3290b/Makefile#L44)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

At the beginning of `clean` `down` is called, so there is no reason to have the both there. Second one should be enough.
</blockquote></details>

:+1: to @jellonek comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225)*

**Comment by pigmej** [comment]
Can we PUBLISH=1 with 1.5 not 1.6 yet? Then I'm fine with merging that PR :)

---

Review status: 7 of 9 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-:-Kfq5zt5UUvtvVI2aVTE:b-fe70km)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-:-KfqBexq6Z2dFGcXl5xh:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 5 of 9 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/225#-:-KfqBtKiwfKy7PhXIE83:bnfp4nl)*

**Pull request merged**
