### PR TITLE
More correct naming for ignore all

### PR DESCRIPTION
**Pull request by zen**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/99)

### CODE REVIEW

**Comment by idvoretskyi** [comment]
LGTM

**Comment by pigmej** [comment]
frankly speaking I preffered *Ignore all* because it was kinda consistent with *ignore this*.

**Comment by zen** [comment]
Well, all is all, children is just chldren. "All" is just too wide, it would imply "Abort" in this case.
If this is not consistent with "this", we should change it to "current". All is very much against good UX, please do not make it more complex than it is

**Comment by pigmej** [comment]
@zen but you created `childer` not children :)

**Pull request merged**
