### PR TITLE
Deployment support

### LINKED ISSUE #94: Add support for deployment.
Right now there is no support for deployment resource in appcontroller.

### PR DESCRIPTION
**Pull request by nebril**
fixes #94

This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/122)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXu3cotz75zJ4yD28ez:-KXu3cotz75zJ4yD28f-:bfmp157) (no related file):*
`scheduler/scheduler_test.go.orig` @nebril ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122)*

**Comment by nebril** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXu3cotz75zJ4yD28ez:-KXu9nXnuBzgJJ63Bo4r:bb6un1j) (no related file):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

`scheduler/scheduler_test.go.orig` @nebril ?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXutoUc_EB-CKtmG0Zr:-KXutoUc_EB-CKtmG0Zs:bccxc04) (no related file):*
I like it. The missing part is functional testing, which we need to tackle *asap*.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-:-KXutqEym9IwRJAJs_fy:bnfp4nl)*

**Comment by gluke77** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[resources/common.go, line 63 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXz50Fwx2eGYYJyDzFJ:-KXz50Fwx2eGYYJyDzFK:bgqrqro) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/58af2b6b06a12852f12e269143417d7b49b54d51/resources/common.go#L63)):*
> ```Go
> }
> 
> func getFactor(factorName string, meta map[string]string) (int32, error) {
> ```

getFactor seems to be a bit weird name. Can we have p[ls something like getPercentage

---

*[resources/deployment.go, line 37 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXz4Dc4qekSBYyXay--:-KXz4Dc5hJ4kfgkL0V6H:b-72l95m) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/58af2b6b06a12852f12e269143417d7b49b54d51/resources/deployment.go#L37)):*
> UpdateMeta
This one is not needed here. We abandoned the approach

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122)*

**Comment by nebril** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[resources/common.go, line 63 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXz50Fwx2eGYYJyDzFJ:-KXzRLVnBmkuG3He5vsh:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/58af2b6b06a12852f12e269143417d7b49b54d51/resources/common.go#L63)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

getFactor seems to be a bit weird name. Can we have p[ls something like getPercentage
</blockquote></details>

Done.

---

*[resources/deployment.go, line 37 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXz4Dc4qekSBYyXay--:-KXzRL4KvzigG0CR4Gul:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/58af2b6b06a12852f12e269143417d7b49b54d51/resources/deployment.go#L37)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

> UpdateMeta
This one is not needed here. We abandoned the approach

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122)*

**Comment by nebril** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXutoUc_EB-CKtmG0Zr:-KXzRMo0i6QJNVYV3sJT:bqp7fdr) (no related file):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

I like it. The missing part is functional testing, which we need to tackle *asap*.
</blockquote></details>

Yeah, but this should not be a part of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122)*

**Comment by pigmej** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-KXutoUc_EB-CKtmG0Zr:-KY-4mILyZHPcaBqEYxB:bi05w9) (no related file):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

Yeah, but this should not be a part of this PR.
</blockquote></details>

Yup, it's not a part of this PR :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/122#-:-KY-Jm74plDP2PP7LQaq:bnfp4nl)*

**Pull request merged**
