### PR TITLE
Enable CI

### PR DESCRIPTION
**Pull request by dshulyak**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/188)

### CODE REVIEW

**Comment by pigmej** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-KboOoek1FL0rlyfFoeD:-KboOoek1FL0rlyfFoeE:b-t5o762) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fa76395fde5c82637bdc3cd19011cab7f6c2c56c/.travis.yml#L9)):*
> v1.5.1

Why not 1.5.2?

---

*[scripts/checkout_k8s.sh, line 9 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-KboOvSekKdt_hGvFmpb:-KboOvSekKdt_hGvFmpc:bfix0o6) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fa76395fde5c82637bdc3cd19011cab7f6c2c56c/scripts/checkout_k8s.sh#L9)):*
> v1.5.1
why not 1.5.2?

---

*[scripts/import.sh, line 12 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-KboP0911IUQLvp1oI1x:-KboP0911IUQLvp1oI1y:bay67b3) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fa76395fde5c82637bdc3cd19011cab7f6c2c56c/scripts/import.sh#L12)):*
> ```Shell
> NUM_NODES=${NUM_NODES:-2}
> TMP_IMAGE_PATH=${TMP_IMAGE_PATH:-/tmp/image.tar}
> MASTER_NAME=${MASTER_NAME=}
> ```

can't we leave it as it was?

---

*[scripts/import.sh, line 13 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-KboP2C23yCDoUuyUjVd:-KboP2C23yCDoUuyUjVe:bay67b3) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fa76395fde5c82637bdc3cd19011cab7f6c2c56c/scripts/import.sh#L13)):*
> ```Shell
> TMP_IMAGE_PATH=${TMP_IMAGE_PATH:-/tmp/image.tar}
> MASTER_NAME=${MASTER_NAME=}
> SLAVE_PATTERN=${SLAVE_PATTERN:-"dind_node_"}
> ```

can't we leave it as it was?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188)*

**Comment by dshulyak** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/import.sh, line 13 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-KboP2C23yCDoUuyUjVd:-KboPS-t-Unz4KeTH35i:b-vs2yne) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fa76395fde5c82637bdc3cd19011cab7f6c2c56c/scripts/import.sh#L13)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

can't we leave it as it was?
</blockquote></details>

i am not sure, because now this is defaults for dind cluster

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188)*

**Comment by dshulyak** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[scripts/checkout_k8s.sh, line 9 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-KboOvSekKdt_hGvFmpb:-KboWAzbiIT5p_zs4WNv:b3k2hsh) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fa76395fde5c82637bdc3cd19011cab7f6c2c56c/scripts/checkout_k8s.sh#L9)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> v1.5.1
why not 1.5.2?
</blockquote></details>

it was here already, i can change it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-:-KbolBz4hbO1a2_l_LGu:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/188#-:-KbonCp-45oLL3R_fq9x:bnfp4nl)*

**Pull request merged**
