### PR TITLE
Wait until k8s-appcontroller pod is running and resources registered

### PR DESCRIPTION
**Pull request by dshulyak**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/158)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/158#-:-KZaQsSgK_C1fWZ5AVbs:bnfp4nl)*

**Comment by nebril** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/common.sh, line 13 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/158#-K_-3I28uyPLiTwwqqjU:-K_-3I28uyPLiTwwqqjV:b-uu3pmp) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/ff6371c18a30e95284dd37821175fe2c212799d6/examples/common.sh#L13)):*
> ```Shell
> function wait-appcontroller {
>    echo "Waiting for pod $APPC to start running"
>    wait-until "$KUBECTL_NAME get pods | grep Running | grep -q $APPC" 10
> ```

If the user doesn't have appcontroller image downloaded it may take much more time. Maybe increase this limit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/158)*

**Comment by dshulyak** [comment]
@nebril I increased up to 20 seconds

**Comment by gluke77** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/158#-:-K_5mWxraIf-zi_4ynM-:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/158#-:-K_8uy91XIVIZWD7tqHF:bnfp4nl)*

**Pull request merged**
