### PR TITLE
 Added human-readable report of deployment 

### PR DESCRIPTION
**Pull request by zefciu**
You can now read a detailed report of the deployment

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/151)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm: 

---

Reviewed 1 of 5 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/151#-:-KYxkLCU6zx5J_IQzrw4:bg7igkv)*

**Comment by nebril** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 98 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/151#-KYxjid1YUBqM-ac17ws:-KYxjid2gKWnVZsCLZiR:b-j22cvd) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/426fb04e5979a42be404d045ca19f9d3ce14fe23/README.md#L98)):*
> ```Markdown
> Use the following command:
> 
> `kubectl exec k8s-appcontroller kubeac -- get-status`
> ```

Why the double dash? (`--`)

---

*[report/report.go, line 48 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/151#-KYxkqD5oK9fwdLickiy:-KYxkqD5oK9fwdLickiz:b-r119nj) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/426fb04e5979a42be404d045ca19f9d3ce14fe23/report/report.go#L48)):*
> []string
I wonder if it wouldn't be better to treat whole report as a string with newlines instead of as a slice of lines, but it's not really critical. Just food for thought.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/151)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[report/report.go, line 48 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/151#-KYxkqD5oK9fwdLickiy:-KYxmactD8OqBfO6KjNP:b-4rkhbf) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/426fb04e5979a42be404d045ca19f9d3ce14fe23/report/report.go#L48)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

> []string
I wonder if it wouldn't be better to treat whole report as a string with newlines instead of as a slice of lines, but it's not really critical. Just food for thought.
</blockquote></details>

I think slice is better, you have more ways to play with it. So I think the current implementation is ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/151)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/151#-:-KYxn_guqGP1jO3X9xA-:bnfp4nl)*

**Comment by zefciu** [comment]
@nebril: I use lists of lines to make indenting easier. If I stored everything as strings, I would have to split and join anytime I want to indent antything.

**Pull request merged**
