### PR TITLE
ThirdPartyResource clients use AC namespace

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/200)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/200#-:-Kd67FWC_derNhrwF1ue:bnfp4nl)*

**Comment by nebril** [comment]
Fixes #192

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/200#-:-KdPj3q26LZ4WAQemoLQ:bnfp4nl)*

**Comment by gluke77** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/get-status.go, line 42 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/200#-KdPugk8cJE35FLuBil1:-KdPugk8cJE35FLuBil2:btat6wj) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/33856991d453093fb3c23e12bd17cc9bc4bf77ac/cmd/get-status.go#L42)):*
> ```Go
> 	}
> 
> 	c, err := client.New(url, nil)
> ```

I'd really like to see separate client.NewForNamespace(url) here and to not use pointers to ns string. I do believe that nil as marker of absent parameter should be avoided whenever possible. Otherwise cod looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/200)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/200#-:-KdQ2mbxfcfkujXgCxqB:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/200#-:-KdQ4-jiI4pb8XJIE5iO:bnfp4nl)*

**Pull request merged**
