### PR TITLE
Failure handling related refactoring

### PR DESCRIPTION
**Pull request by gluke77**
This is the first part of refactorings to allow failure handling

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/125)

### CODE REVIEW

**Comment by nebril** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scheduler/scheduler.go, line 87 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzH7Q9zU-F6oQNHjkV:-KXzH7Q9zU-F6oQNHjkW:b-shwm2z) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L87)):*
> ```Go
> }
> 
> // Create does not creates a scheduled resource immediately, but updates status
> ```

s/creates/create

---

*[scheduler/scheduler.go, line 330 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzHv3y9y7gX-svOg6Y:-KXzHv3y9y7gX-svOg6Z:b3r2s20) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L330)):*
> ```Go
> 			for {
> 				time.Sleep(CheckInterval)
> 				var isFinished bool
> ```

This variable declaration seems not necessary, you could just use `:=` in line 331

---

*[scheduler/scheduler.go, line 331 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzID2CvaZTmtlVA-lH:-KXzID2CvaZTmtlVA-lI:b-4n8cha) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L331)):*
> ```Go
> 				time.Sleep(CheckInterval)
> 				var isFinished bool
> 				isFinished, err = r.IsFinished()
> ```

Where is this `err` handled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125)*

**Comment by gluke77** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scheduler/scheduler.go, line 87 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzH7Q9zU-F6oQNHjkV:-KXzJmvoFgHchpBU4eFN:b2nid5l) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L87)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

s/creates/create
</blockquote></details>

tnx

---

*[scheduler/scheduler.go, line 330 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzHv3y9y7gX-svOg6Y:-KXzJLKEzA1sfX3mPTwk:b-t1b5ll) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L330)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

This variable declaration seems not necessary, you could just use `:=` in line 331
</blockquote></details>

I tried. Didn't work for me. Probably because 'for' adds scoping here.

---

*[scheduler/scheduler.go, line 331 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzID2CvaZTmtlVA-lH:-KXzJhUB_t8LIJRAjMH6:b-p2d11c) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L331)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

Where is this `err` handled?
</blockquote></details>

5 lines below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125)*

**Comment by nebril** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scheduler/scheduler.go, line 330 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzHv3y9y7gX-svOg6Y:-KXzPkITdKPdlgTXXjkc:b-ykczx4) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L330)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

I tried. Didn't work for me. Probably because 'for' adds scoping here.
</blockquote></details>

Ah, it's because err is handled outside of the loop. Got it. 

---

*[scheduler/scheduler.go, line 331 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzID2CvaZTmtlVA-lH:-KXzQ-UyMJIE9UO266sM:b-dx15pg) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L331)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

5 lines below
</blockquote></details>

Maybe we should aggregate errors into a slice and show all errors that occurred instead of only the last one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125)*

**Comment by gluke77** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scheduler/scheduler.go, line 331 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzID2CvaZTmtlVA-lH:-KYDNZxo6NSB47H1Al-b:bptgc9u) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L331)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

Maybe we should aggregate errors into a slice and show all errors that occurred instead of only the last one?
</blockquote></details>

I'd rather not. In fact current implementation does not return error if not finished yet. And if it will chenge later, we here imply only one way to 'process an error' -- log and continue loop. So I would do that incsede the function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125)*

**Comment by pigmej** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scheduler/scheduler.go, line 331 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-KXzID2CvaZTmtlVA-lH:-KYDOsX3Uoq7Zd6LLN8h:b-kb0lfv) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/304fb0a03d2603ca26ebb5a48b51312ee00fe88b/scheduler/scheduler.go#L331)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

I'd rather not. In fact current implementation does not return error if not finished yet. And if it will chenge later, we here imply only one way to 'process an error' -- log and continue loop. So I would do that incsede the function.
</blockquote></details>

:+1: @gluke77 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-:-KYE48pELVLvhQjvIdpC:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-:-KYIzS6CETql1QAuc0W7:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/125#-:-KYJ9LJU05nGlxhJw9oU:bnfp4nl)*

**Pull request merged**
