### PR TITLE
Improved get-status

### PR DESCRIPTION
**Pull request by zefciu**
Improved get-status to yield more data. Needs some smoke-testing and
presentation, but the logic can be reviewed

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/105)

### CODE REVIEW

**Comment by gluke77** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[scheduler/scheduler.go, line 455 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KWrNIRbJ0NDsBhbuRiE:-KWrNIRc6NMxaGWK18W9:b-winjqe) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c957e5b7b39442e4335fafd650fe0debdc43304f/scheduler/scheduler.go#L455)):*
> ```Go
> 			isBlocked = true
> 		}
> 		dependencies[i] = depReport
> ```

Can we use 'append' instead and get rid of indexing here? Using index we won't gain much in performance but decrease readability?

---

*[scheduler/scheduler.go, line 477 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KWrNdixb4hqI0PD6hpW:-KWrNdixb4hqI0PD6hpX:b-ya81ng) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c957e5b7b39442e4335fafd650fe0debdc43304f/scheduler/scheduler.go#L477)):*
> ```Go
> 	for key, resource := range *graph {
> 		depReport := resource.GetNodeReport(key)
> 		report[i] = depReport
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by zefciu** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[scheduler/scheduler.go, line 455 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KWrNIRbJ0NDsBhbuRiE:-KWrnNL7QQ3JTw5RxPXJ:bx4s1wm) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c957e5b7b39442e4335fafd650fe0debdc43304f/scheduler/scheduler.go#L455)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary>
> Can we use 'append' instead and get rid of indexing here? Using index we won't gain much in performance but decrease readability?
</details>
OK, that's just my golang indolence. Will correct it.

---

*[scheduler/scheduler.go, line 477 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KWrNdixb4hqI0PD6hpW:-KWrnTRTWgQQNlsAcCGF:b32w0x) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c957e5b7b39442e4335fafd650fe0debdc43304f/scheduler/scheduler.go#L477)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary>
> Same as above
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by zefciu** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[scheduler/scheduler.go, line 455 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KWrNIRbJ0NDsBhbuRiE:-KX60CWpduaJaka_oE0X:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c957e5b7b39442e4335fafd650fe0debdc43304f/scheduler/scheduler.go#L455)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary>
> OK, that's just my golang indolence. Will correct it.
</details>
Done.

---

*[scheduler/scheduler.go, line 477 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KWrNdixb4hqI0PD6hpW:-KX60BHyf6r0h2jfEt_B:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c957e5b7b39442e4335fafd650fe0debdc43304f/scheduler/scheduler.go#L477)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary>
> OK
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KX6ygmTZ1eIPXnWzBZN:bnfp4nl)*

**Comment by pigmej** [comment]
@nebril / @gluke77  please take a look

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KX6yiweTqsGaN4PaJft:brct3uf)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KX71_gxlTJDydnobbRT:-KX71_gxlTJDydnobbRU:b-bkkqa8) (no related file):*
In fact, @zefciu travis fails, so I'd like to remove my lgtm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by gluke77** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[resources/replicaset.go, line 68 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KX7NGOLUa3bp6wFG7Km:-KX7NGOLUa3bp6wFG7Kn:bie00pl) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/a3048fe501cd01c8fe548a855667a415b9dfc9a7/resources/replicaset.go#L68)):*
> ```Go
> }
> 
> func replicatSetReport(r unversioned.ReplicaSetInterface, name string, meta map[string]string) report.DependencyReport {
> ```

is it a typo? I mean the first 't' replicatSetReport

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by gluke77** [comment]
Apart from the typo (?) I'd like to say that I actually don't really like it. Sorry @zefciu, I should have pointed it out earlier. I mean I think 'GetDependencyReport' should not belong to 'Resource' interface. At least I'd like to see it in a separate interface. (I'd actually moved New, NewExisting and NameMatches to a separate interface as well). But look, each implementation of 'GetDependencyReport', except one, does the same and even does not utilize it's parameter, the map. So it really looks like a weak abstraction. You're kinda trying to pull object-oriented design on what it does not really fit, IMAO. I know switch by type really sucks, but in this case I'd probably be ok with it rather than pollute Resource interface. Or, I could be completely wrong and this OOD is viable if you expect more complicated implementations of GetDependencyReport in the future.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KX7NvWkuoU7Ue3HqiWE:b-382bjm)*

**Comment by nebril** [comment]
@gluke77 I agree with you on some points (I also think that this should be handled by another interface than Resource), but I think that switching by type should be avoided by all costs, as it makes it really hard to add new resource types.

I propose that we add new interface (as you suggested) with GetDependencyReport function, implement it by new struct type (e.g. `DependencyReporter` and add it to all Resource implementations (except for ReplicaSet) by composition, so all Resources implement this new interface. What do you think?

**Comment by zefciu** [comment]
I really the idea of type switch here. We might add support for more object types in the future and the switch will get terribly complicated. In python world I would use inheritance. Here I would stick with composition, as nihilifer suggested.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KXAWeINLq0nfkhg58iw:b-1obk39)*

**Comment by zefciu** [comment]
I have tried to use interface composition here and I believe this would complicate things too much, while giving us little profit. We would still need all our resources to implement both the "Resource" interface and the "DependencyReporter" interface, while adding a lot of complicated casting logic.

What I could do however is using the struct composition to make the code more DRY. Would it be OK with you? @gluke77 @pigmej @nebril

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KXBDj6pOHEOA4GR4wJ6:b5fwew5)*

**Comment by nebril** [comment]
I am fine with this approach.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KXBFG4G6t4-dfN-mBO7:b-n2o64w)*

**Comment by gluke77** [comment]
Now it looks much much better for me, except naming. Could you pls rename Resource->BaseResource and Reporter->Resource?

---

Reviewed 1 of 13 files at r1, 1 of 13 files at r3.
Review status: 2 of 14 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[report/report.go, line 35 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIq4N29hJ-d76SLSbi:-KYIq4N34QIc2rZchzDz:bs5w0js) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/report/report.go#L35)):*
> ```Go
> 
> // SimpleDependencyReport returns a report for classic binary cases
> func SimpleDependencyReport(name string, status string, err error) interfaces.DependencyReport {
> ```

Why don't just put the implementation into SimpleReporter.GetDependencyReport?  We don't seem to need it as a separate function

---

*[resources/petset.go, line 129 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYInmCt3jdwWEFOLTfA:-KYInmCt-bHwERLnK6m_:bueslek) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/resources/petset.go#L129)):*
> ```Go
> 
> // GetDependencyReport returns a DependencyReport for this Petset
> func (p PetSet) GetDependencyReport(_ map[string]string) interfaces.DependencyReport {
> ```

This seems to be a leftover or an artifact of improper merge. I don't see how this implementationn differs from the one from SimpleReporter.

---

*[resources/petset.go, line 173 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIoCmuCJOk9uztCckc:-KYIoCmuBBhtwnopntrC:b-7ropln) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/resources/petset.go#L173)):*
> ```Go
> 
> // GetDependencyReport returns a DependencyReport for this Petset
> func (p ExistingPetSet) GetDependencyReport(_ map[string]string) interfaces.DependencyReport {
> ```

ditto

---

*[resources/replicaset.go, line 73 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIogeH5igtHakFrzBD:-KYIogeJ12heDEW002fa:b-k3g5eh) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/resources/replicaset.go#L73)):*
> ```Go
> 		return report.ErrorReport(name, err)
> 	}
> 	successFactor, err := getSuccessFactor(meta)
> ```

getSuccessFactor -- please consider using generic 'getPercentage'

---

*[scheduler/scheduler.go, line 100 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIwwdp127Fhz09SPMT:-KYIwwdp9yGmFij-ESBO:bw2mepp) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L100)):*
> switch r.Reporter.GetResource().(type) {

This is an extremely ugly chunk of code (existing one, not that you added))) that makes you introduce this GetResource -- could you please get rid of GetResource completely and in this particular case use swich by kind extracted from getKey(), as a temporarily solution 

---

*[scheduler/scheduler.go, line 449 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIpMQq54ENS14p_kSy:-KYIpMQqDw9PkuHpX8Q3:bwjner0) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L449)):*
> ```Go
> 		ready = status == "ready"
> 	}
> 	i := 0
> ```

since we use 'append' we don't need the counter any more

---

*[scheduler/scheduler.go, line 458 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIwRpzEsjVAKmlo76v:-KYIwRpz0jagOtmNmFR7:b-agjzdz) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L458)):*
> ```Go
> 		}
> 		dependencies = append(dependencies, depReport)
> 		r.RUnlock()
> ```

^^ I'm not sure that we really need locks here, but anyway it is a good idea to release unused resource ASAP, in this case right afrer r.GetDependencyReport

---

*[scheduler/scheduler.go, line 476 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIw2m81BPoFXpLOCm9:-KYIw2m93MA-1xBiVzZO:bjq2ajv) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L476)):*
> i := 0
we don't need this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYIy0x66QK6M-dBWo1B:b8yp24t)*

**Comment by zefciu** [comment]
Review status: 1 of 20 files reviewed at latest revision, 12 unresolved discussions.

---

*[report/report.go, line 35 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIq4N29hJ-d76SLSbi:-KYZ9uGsM515QIlbwfbR:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/report/report.go#L35)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

Why don't just put the implementation into SimpleReporter.GetDependencyReport?  We don't seem to need it as a separate function
</blockquote></details>

Done.

---

*[resources/petset.go, line 129 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYInmCt3jdwWEFOLTfA:-KYZ9vuItam5qqlrBtaZ:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/resources/petset.go#L129)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

This seems to be a leftover or an artifact of improper merge. I don't see how this implementationn differs from the one from SimpleReporter.
</blockquote></details>

Done.

---

*[resources/petset.go, line 173 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIoCmuCJOk9uztCckc:-KYZ9whQhDqyO1z0pJ2i:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/resources/petset.go#L173)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[scheduler/scheduler.go, line 100 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIwwdp127Fhz09SPMT:-KYZA0vqU9TS4gzP5fQw:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L100)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

> switch r.Reporter.GetResource().(type) {

This is an extremely ugly chunk of code (existing one, not that you added))) that makes you introduce this GetResource -- could you please get rid of GetResource completely and in this particular case use swich by kind extracted from getKey(), as a temporarily solution 
</blockquote></details>

Done.

---

*[scheduler/scheduler.go, line 449 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIpMQq54ENS14p_kSy:-KYZA1tjl_mmxpiSmAeq:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L449)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

since we use 'append' we don't need the counter any more
</blockquote></details>

Done.

---

*[scheduler/scheduler.go, line 458 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIwRpzEsjVAKmlo76v:-KYZA2RynlKUqBAFWkBJ:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L458)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

^^ I'm not sure that we really need locks here, but anyway it is a good idea to release unused resource ASAP, in this case right afrer r.GetDependencyReport
</blockquote></details>

Done.

---

*[scheduler/scheduler.go, line 476 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIw2m81BPoFXpLOCm9:-KYZA36bgfQCqP28URCw:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/scheduler/scheduler.go#L476)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

> i := 0
we don't need this

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by zefciu** [comment]
Review status: 1 of 20 files reviewed at latest revision, 12 unresolved discussions.

---

*[resources/replicaset.go, line 68 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KX7NGOLUa3bp6wFG7Km:-KYZAYx3ZrKmTJDo7f7X:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/a3048fe501cd01c8fe548a855667a415b9dfc9a7/resources/replicaset.go#L68)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

is it a typo? I mean the first 't' replicatSetReport
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by zefciu** [comment]
Done

---

Review status: 1 of 20 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KX71_gxlTJDydnobbRT:-KYZAgs9M7tsG1eyD5FM:bb6un1j) (no related file):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

In fact, @zefciu travis fails, so I'd like to remove my lgtm.
</blockquote></details>

Done

---

*[resources/replicaset.go, line 73 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYIogeH5igtHakFrzBD:-KYZAdhXXJOYngBZ_EVt:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/7ba3d7d1df7c381704dad68fde88c1880148dee9/resources/replicaset.go#L73)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

getSuccessFactor -- please consider using generic 'getPercentage'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYZAf69cWJEJQV3BTVZ:bb6un1j)*

**Comment by gluke77** [comment]
I see you didn't do the renaming. Do you object or just forget?

---

Reviewed 1 of 18 files at r4.
Review status: 2 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[resources/replicaset.go, line 68 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KX7NGOLUa3bp6wFG7Km:-KYZKzcPO2w5FY73nM_j:bx92t3b) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/a3048fe501cd01c8fe548a855667a415b9dfc9a7/resources/replicaset.go#L68)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hm... I actually don't see it changed. Did you forget it to commit?

---

*[scheduler/scheduler.go, line 141 at r4](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYZLWupbWJ6jY46VrI2:-KYZLWuqYu1f4z_9cKSO:bw916i6) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c76764b45f3229c978e35299f7a3bb4feef66c24/scheduler/scheduler.go#L141)):*
> ```Go
> 		req.RLock()
> 		meta := req.Meta[sr.Key()]
> 		if strings.HasPrefix(req.Reporter.Key(), "service") {
> ```

JFYI, you could use req.Key() here. This is not true for Status because both ScheduledResource and Resource have it

---

*[scheduler/scheduler.go, line 274 at r4](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYZMhCaU3zM22h9J8uC:-KYZMhCbCjONgawh-EL7:bjfgpwt) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c76764b45f3229c978e35299f7a3bb4feef66c24/scheduler/scheduler.go#L274)):*
> ```Go
> 
> 		if r.Pod != nil {
> 			sr = NewScheduledResourceFor(report.SimpleReporter{Resource: resources.NewPod(r.Pod, c.Pods())})
> ```

Oh, man, i missed this place. This does not look good. we should not be aware here how to construct the resource. So we should either use Pod{}.New(...) here (which is weird) or just move this creation logic from Pod{}New(..) to NewPod(..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYZNWPua2BaXYChDvpG:b-g4s93b)*

**Comment by zefciu** [comment]
Which one? The 'replicat' thing is there

---

Review status: 2 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[resources/replicaset.go, line 68 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KX7NGOLUa3bp6wFG7Km:-KYm7ze8Qr2EBIg15xHA:b-7lfufc) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/a3048fe501cd01c8fe548a855667a415b9dfc9a7/resources/replicaset.go#L68)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

hm... I actually don't see it changed. Did you forget it to commit?
</blockquote></details>

Repushed. Now it is there.

---

*[scheduler/scheduler.go, line 141 at r4](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYZLWupbWJ6jY46VrI2:-KYm7OC5Ku6e4DiiW0ZW:b-pn4hfp) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c76764b45f3229c978e35299f7a3bb4feef66c24/scheduler/scheduler.go#L141)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

JFYI, you could use req.Key() here. This is not true for Status because both ScheduledResource and Resource have it
</blockquote></details>

Should I change it or can it stay? It is a little more readable this way, I believe.

---

*[scheduler/scheduler.go, line 274 at r4](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYZMhCaU3zM22h9J8uC:-KYm7aHQieAOZ99FDKuv:b-yazwl6) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c76764b45f3229c978e35299f7a3bb4feef66c24/scheduler/scheduler.go#L274)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

Oh, man, i missed this place. This does not look good. we should not be aware here how to construct the resource. So we should either use Pod{}.New(...) here (which is weird) or just move this creation logic from Pod{}New(..) to NewPod(..)
</blockquote></details>

Still however the NewPod is sometimes used in other contexts. It would require much bigger refactor to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYm86WTvrUsvWmzMvrS:bkl264u)*

**Comment by pigmej** [comment]
Review status: 2 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[glide.lock, line 19 at r5](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYmHofCw9igJkgtHyA5:-KYmHofD57UxyrcV3CMu:bfhlja3) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/4b8e42b1e58a722030bc5a0123c2d63cd661a455/glide.lock#L19)):*
> github.com/coreos/go-systemd

What's that? And what for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by pigmej** [comment]
Review status: 1 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[glide.lock, line 19 at r5](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYmHofCw9igJkgtHyA5:-KYmM3kdY2h7ozVkPCJi:b-lxe71o) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/4b8e42b1e58a722030bc5a0123c2d63cd661a455/glide.lock#L19)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> github.com/coreos/go-systemd

What's that? And what for?
</blockquote></details>

OK

Thanks for reverting it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by pigmej** [comment]
:lgtm: but let's address @gluke77 concerns too.

---

Reviewed 2 of 13 files at r3, 16 of 18 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYmNOR-YF57cFwfI1Em:bmu77ac)*

**Comment by gluke77** [comment]
I meant renaming interfaces, Resource->BaseResource, Reporter -> Resource. It's just i think 'Reporter' is really a weird name for the thing it represents. I do remember that it was me who suggested it, but i should admit that it was not a good idea.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[scheduler/scheduler.go, line 141 at r4](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYZLWupbWJ6jY46VrI2:-KYmVHnQ1urGWnDWwAW5:b346odo) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c76764b45f3229c978e35299f7a3bb4feef66c24/scheduler/scheduler.go#L141)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

Should I change it or can it stay? It is a little more readable this way, I believe.
</blockquote></details>

OK You absolute could keep it, and I'd agree that it's more readable.

---

*[scheduler/scheduler.go, line 274 at r4](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYZMhCaU3zM22h9J8uC:-KYmViCmQJfglkriHR8j:b-f6hdsd) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/c76764b45f3229c978e35299f7a3bb4feef66c24/scheduler/scheduler.go#L274)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

Still however the NewPod is sometimes used in other contexts. It would require much bigger refactor to do it.
</blockquote></details>

OK but let's do it asap in follow-up commit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYmUhOV669m1MZZhYYh:b-edhzca)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/get-status.go, line 24 at r6](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYmWVieFJxBw6zPgwgt:-KYmWVifYzFp23Ck9kLO:b-nm0p0p) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/a44ef943fb7a61248f94e47501ff1cd69d9cf362/cmd/get-status.go#L24)):*
> ```Go
> 	}
> 
> 	getJSON, err := cmd.Flags().GetBool("json")
> ```

Better name for this would be `asJSON`.

---

*[cmd/get-status.go, line 73 at r6](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYmWdcgl-WL-mvy3O52:-KYmWdcgl-WL-mvy3O53:b2nreh6) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/a44ef943fb7a61248f94e47501ff1cd69d9cf362/cmd/get-status.go#L73)):*
> ```Go
> 	run.Flags().StringVarP(&labelSelector, "label", "l", "", "Label selector. Overrides KUBERNETES_AC_LABEL_SELECTOR env variable in AppController pod.")
> 
> 	var getJSON bool
> ```

Same as above.

---

*[examples/extended/create.sh, line 39 at r6](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-KYmX5r-xWeK3Jy4DvSE:-KYmX5r-xWeK3Jy4DvSF:b-hetdxl) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/a44ef943fb7a61248f94e47501ff1cd69d9cf362/examples/extended/create.sh#L39)):*
> ```Shell
> cat configmap1.yaml | $KUBECTL_NAME exec -i k8s-appcontroller kubeac wrap | $KUBECTL_NAME create -f -
> 
> cat secrets.yaml | $KUBECTL_NAME exec -i k8s-appcontroller kubeac wrap | $KUBECTL_NAME create -f -
> ```

You are adding there `s`, and later diff have rename of `secrets` to `secret`.
This is also covered in merged #143 so you simply need to rebase again on master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r1, 2 of 13 files at r3, 13 of 18 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYmsCyq7BjV73JM-lEH:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm: but @gluke77 PTAL.

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYmx226TjlYprSTUUf_:bk5kufr)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/105#-:-KYn28gRUH7hWTsxuPhs:bnfp4nl)*

**Pull request merged**
