### PR TITLE
Graph flows

### PR DESCRIPTION
**Pull request by istalker2**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/212)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/research/flows.md, line 38 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KebxbcrwoaY8C1rEltt:-KebxbcrwoaY8C1rEltu:bqxab97) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L38)):*
> https://github.com/istalker2/ac-etcd

I'm not 100% sure if linking to 3rd party repo (looking from AC repo perspective) is right there, but it's not that I'm against it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212)*

**Comment by nebril** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[docs/research/flows.md, line 5 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiC7hG0dSzaftt7Nwn:-KeiC7hG0dSzaftt7Nwo:b7oz585) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L5)):*
> ```Markdown
> 
> Flow is a way to designate a part of AC resource graph (i.e. its subgraph) and then use
> it as a atomic in other parts of a graph. Thus the deployment of a bigger system may be
> ```

`as a atomic` seems to not be correct. `as an atomic`, but I would also change `atomic` to `vertex`, so my final proposal is `as vertex`.

---

*[docs/research/flows.md, line 13 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiCiJtRcIlwQ-Ahhvt:-KeiCiJtRcIlwQ-Ahhvu:bfqad6t) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L13)):*
> ```Markdown
> and an application, that depends on it, both database and the application become such
> components and the main graph has just these two nodes, whereas there are separate
> subgraphs for each of them. If then one want to change the database subgraph he is free
> ```

`s/If then one want/If then one wants`

---

*[docs/research/flows.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiCoyY7ScszFmlGAor:-KeiCoyY7ScszFmlGAos:brleejt) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L14)):*
> ```Markdown
> components and the main graph has just these two nodes, whereas there are separate
> subgraphs for each of them. If then one want to change the database subgraph he is free
> to do say without a need to make any changes to the application subgraph since it doesn't
> ```

`s/say/so`

---

*[docs/research/flows.md, line 18 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiCurbiudk92a2A3Kb:-KeiCurbiudk92a2A3Kc:b-f0k8qn) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L18)):*
> ```Markdown
> whole.
> 
> Flows are a means to define such components, their scope within the graph and their
> ```

`s/are a means/are means`

---

*[docs/research/flows.md, line 26 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiDu-2MmfFC4xY3ma4:-KeiDu-2MmfFC4xY3ma5:b-dc7lip) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L26)):*
> ```Markdown
>   AppController CLI
> * Can be replicated, i.e. produce more than one deployment of the subgraph
> * Each flow replica has a unique name which can be substituted into dependent resource
> ```

probably `s/substituted into/substituted with`

---

*[docs/research/flows.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiE1UTP5s7Ob2PJMF9:-KeiE1UTP5s7Ob2PJMFA:b-obn7n6) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L27)):*
> ```Markdown
> * Can be replicated, i.e. produce more than one deployment of the subgraph
> * Each flow replica has a unique name which can be substituted into dependent resource
>   names or anywhere in their definition. Thus each flow replica might produce both
> ```

I don't understand this sentence.  "Each flow replica has a unique name which can be substituted into dependent resource names or anywhere in their definition." I don't know what "or anywhere in their definition" means in this context.

---

*[docs/research/flows.md, line 30 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiEK3xfStonGrSubPV:-KeiEK3xfStonGrSubPW:brz7se6) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L30)):*
> ```Markdown
>   different resources (if the replica name is used as part of its name) and share
>   common resources
> * Can be parametrized. Parameter values can be used in resource defiitions the same
> ```

`s/defiitions/definitions`

---

*[docs/research/flows.md, line 36 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiEW2t8D4T_awxVJ2A:-KeiEW2t8D4T_awxVJ2B:bb8mch8) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L36)):*
> https://docs.google.com/document/d/1UH9r9X3AaOND_KZO0Qslp6iPkt526PMDpG29B4L1sVQ/edit?usp=sharing
Not sure about putting google doc here, maybe @jnowak what do you think?

---

*[docs/research/flows.md, line 38 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KebxbcrwoaY8C1rEltt:-KeiEaUbwEHINHiB2F8Y:bc4k889) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L38)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> https://github.com/istalker2/ac-etcd

I'm not 100% sure if linking to 3rd party repo (looking from AC repo perspective) is right there, but it's not that I'm against it.
</blockquote></details>

I am OK with that, google doc above makes me more nervous TBH.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[docs/research/flows.md, line 38 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KebxbcrwoaY8C1rEltt:-KeiGCqrgeaMRI7ScGzO:byaccdx) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L38)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

I am OK with that, google doc above makes me more nervous TBH.
</blockquote></details>

GDoc can be merged when everything will be finished.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[docs/research/flows.md, line 33 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiK6pEfKwbMwbdeRHw:-KeiK6pEfKwbMwbdeRHx:b-56gqry) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L33)):*
> May be stable (idempotent) or not. Stable flows produce the same replica names on each run, which result in the same resource graph

I'm not sure if I understand this English :)

---

*[docs/research/flows.md, line 36 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiEW2t8D4T_awxVJ2A:-KeiK1zO74eXFNjxE6PV:bm7hm3b) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L36)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

> https://docs.google.com/document/d/1UH9r9X3AaOND_KZO0Qslp6iPkt526PMDpG29B4L1sVQ/edit?usp=sharing
Not sure about putting google doc here, maybe @jnowak what do you think?
</blockquote></details>

gdoc is ok at this stage, later we will export and merge it there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/research/flows.md, line 5 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiC7hG0dSzaftt7Nwn:-KeiHmUVGKFTnFMaetHP:b-xhg1sb) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L5)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

`as a atomic` seems to not be correct. `as an atomic`, but I would also change `atomic` to `vertex`, so my final proposal is `as vertex`.
</blockquote></details>

`as a vertex`?

---

*[docs/research/flows.md, line 6 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiHtgOYPcgedpvvPGv:-KeiHtgOYPcgedpvvPGw:bpi0eyi) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L6)):*
> ```Markdown
> Flow is a way to designate a part of AC resource graph (i.e. its subgraph) and then use
> it as a atomic in other parts of a graph. Thus the deployment of a bigger system may be
> split into smaller reusable components and then compose the overall deployment from these
> ```

`Thus the deployment of a bigger system may be split into smaller reusable components.` imo rest should be dropped.

---

*[docs/research/flows.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiCoyY7ScszFmlGAor:-KeiJKFaIQv3UR5wim0-:b-nuv0m7) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L14)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

`s/say/so`
</blockquote></details>

to do this without a need to do any changes in the application subgraph

---

*[docs/research/flows.md, line 33 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212#-KeiK6pEfKwbMwbdeRHw:-KeiLJxPpWZ62RCE3tvP:b-q90e2m) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/fc1e6553ff1912e1b49bdc63a3ce2222b43b8dcf/docs/research/flows.md#L33)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> May be stable (idempotent) or not. Stable flows produce the same replica names on each run, which result in the same resource graph

I'm not sure if I understand this English :)

</blockquote></details>

Missing explanation for unstable part even if it's opposite for `same graph`. Maybe this should be rephrased as: May be unstable, which results in different graphs with different replica names on each run, or stable (idempotent), resulting in same replica names (so in effect same resource graph) for each run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/212)*

**Pull request closed without merging**
