### PR TITLE
Use dockerhub hooks to make final image smaller

### PR DESCRIPTION
**Pull request by pigmej**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/115)

### CODE REVIEW

**Comment by nebril** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[hooks/pre-build, line 4 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-KXf8BU8N3ziWJIqfgu3:-KXf8BU8N3ziWJIqfgu4:b-nlhv97) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/5d397d661c607a611b35bfed21a5d32fc5ffbbdc/hooks/pre-build#L4)):*
> ```
> echo "=> Building the binary"
> 
> docker run --privileged -w /go/src/github.com/Mirantis/k8s-AppController -v $(pwd)/../:/go/src/github.com/Mirantis/k8s-AppController golang:alpine sh -c "echo \"@community http://dl-cdn.alpinelinux.org/alpine/edge/community\" >> /etc/apk/repositories; apk --no-cache add git glide@community; glide install --strip-vendor; go build -o kubeac; mkdir -p /opt/kubeac"
> ```

Please break this line so it's at least a bit readable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115)*

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 7 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-KXfEgIVHus6TmdRgba0:-KXfEgIVHus6TmdRgba1:bndlr6n) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/5d397d661c607a611b35bfed21a5d32fc5ffbbdc/Dockerfile#L7)):*
> ```Dockerfile
> 
> RUN mkdir -p /etc/sv/ac
> RUN mkdir -p /opt/kubeac
> ```

Please join above 4 lines (with " && \") and add to them that with `touch` invocation.

---

*[hooks/pre-build, line 4 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-KXf8BU8N3ziWJIqfgu3:-KXfF0CVIiLSQTv7Eyfd:bxkmk56) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/5d397d661c607a611b35bfed21a5d32fc5ffbbdc/hooks/pre-build#L4)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

Please break this line so it's at least a bit readable
</blockquote></details>

:+1: + remove unnecessary `mkdir -p` invocation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115)*

**Comment by pigmej** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 7 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-KXfEgIVHus6TmdRgba0:-KXg-yXd5H7I9mysWNGQ:bb8g9ej) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/5d397d661c607a611b35bfed21a5d32fc5ffbbdc/Dockerfile#L7)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please join above 4 lines (with " && \") and add to them that with `touch` invocation.
</blockquote></details>

Will do when it's ready :)

---

*[hooks/pre_build, line 4 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-KXf8BU8N3ziWJIqfgu3:-KXg008weymcx6iOCx5c:b-r6sa6e) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/5d397d661c607a611b35bfed21a5d32fc5ffbbdc/hooks/pre_build#L4)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

:+1: + remove unnecessary `mkdir -p` invocation.
</blockquote></details>

Will do when it's ready.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115)*

**Comment by pigmej** [comment]
Final compressed image size is 12MB. ( http://www.imagebam.com/image/234f4f517222207 ) reduced from 96MB.

**Comment by pigmej** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 7 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-KXfEgIVHus6TmdRgba0:-KXgXr5Yp2bXPpOs7Tml:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/5d397d661c607a611b35bfed21a5d32fc5ffbbdc/Dockerfile#L7)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Will do when it's ready :)
</blockquote></details>

Done.

---

*[hooks/pre-build, line 4 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-KXf8BU8N3ziWJIqfgu3:-KXgXs5FLQmroNa5eNry:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/5d397d661c607a611b35bfed21a5d32fc5ffbbdc/hooks/pre-build#L4)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Will do when it's ready.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-:-KXgma3NFkMRSfonX8bc:bnfp4nl)*

**Comment by gluke77** [comment]
Awesome job! There is one issue though -- with this PR we won't be able to build the docker image locally via plain `docker build .` which could be useful. So I suggest either to update the README as for how to build it locally or to save previous Dockerfile as, say Dockerfile.local,  so we could still use it.

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-:-KXj4wZW6kd6vDumDjI2:b-ivditb)*

**Comment by jellonek** [comment]
So there is needed additional info in README that local images build requires built binary, which can be generated using `./hooks/pre_build`.

It would be nice to add `Makefile` at some point of time which could combine these steps also adding a possibility to export generated image into tar file.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-:-KXj90c2X84M8ijyaXCk:b4pydt6)*

**Comment by nebril** [comment]
That's true, also - you won't be able to build an image on OsX. Maybe move old Dockerfile to Dockerfile.local file which will be used for easy local image building regardless of platform?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-:-KXjL2SejQH-s-g7wKrs:b-pye5v6)*

**Comment by jellonek** [comment]
Again, with little help of `Makefile` or manually setting environment variables it's still possible even on mac:
Please try: `env GOOS=linux GOARCH=amd64 go build -o kubeac`
So also this could be added into README or even - into `pre_build`.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-:-KXjMaYPujglfbH1oli0:b2e44zj)*

**Comment by gluke77** [comment]
@jellonek For such a spell we definitely need a target in Makefile

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-:-KXjNcfGKwthCcHcdc43:bmwkndm)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/115#-:-KXjWFGFzUvsxQPiJJZn:bnfp4nl)*

**Pull request merged**
