### PR TITLE
Add back support for 1.4 petsets

### PR DESCRIPTION
**Pull request by dshulyak**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/163)

### CODE REVIEW

**Comment by dshulyak** [comment]
Current approach won't work for several reasons:
- no way to register same api group multiple times from different packages (maybe can be fixed in upstream)
- problems with fake clientset integration

I will try to use clientset from kubernetes/1.4 once again...

**Comment by nebril** [comment]
Reviewed 28 of 37 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/mocks/resdefs.go, line 40 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-K_ZU4SEXIvFGtZDNlDq:-K_ZU4SFxczqx36QE0Xo:b32v57) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9920ac536e7ba4b6be65a52f49f2490f1465b338/pkg/mocks/resdefs.go#L40)):*
> ```Go
> 		n := strings.Join(splitted[1:], "/")
> 
> 		switch objectType {
> ```

+1

---

*[pkg/resources/common.go, line 129 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-K_ZWAYe84RF6pSIZaOO:-K_ZWAYe84RF6pSIZaOP:bcnr9ca) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9920ac536e7ba4b6be65a52f49f2490f1465b338/pkg/resources/common.go#L129)):*
> ```Go
> }
> 
> func podsStateFromLabels(apiClient client.Interface, objLabels map[string]string) (string, error) {
> ```

I think petsets/statefulsets can use full-fledged selectors (e.g. `matchExpressions` selectors) instead of only equality based selectors? Not saying this should be done in this PR (it's already big as it is), but we should add an issue about it and fix it in future.

---

*[pkg/resources/common.go, line 136 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-K_ZVtyWtMlhrZy3iJXu:-K_ZVtyWtMlhrZy3iJXv:b-zayktf) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9920ac536e7ba4b6be65a52f49f2490f1465b338/pkg/resources/common.go#L136)):*
> ```Go
> 	stringSelector := strings.Join(labelSelectors, ",")
> 	selector, err := labels.Parse(stringSelector)
> 	log.Printf("%s,%v\n", stringSelector, selector)
> ```

Please make this log more elaborate or remove it.

---

*[pkg/resources/service.go, line 82 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-K_ZUnV4bTvhHr8CuirG:-K_ZUnV4bTvhHr8CuirH:b4nnv84) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9920ac536e7ba4b6be65a52f49f2490f1465b338/pkg/resources/service.go#L82)):*
> ```Go
> 			statefulsets, err := apiClient.StatefulSets().List(options)
> 			if err != nil {
> 				return "error", err
> ```

I guess this superseeds my PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163)*

**Comment by nebril** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-:-Ka7ClBX94OyKi4nXmXC:bnfp4nl)*

**Comment by jellonek** [comment]
Quite big, so IMO additional reviewer is needed, but :lgtm: 

---

Reviewed 27 of 37 files at r1, 6 of 10 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.codeclimate.yml, line 17 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-Ka7DZvPXTX8zfY48jJz:-Ka7DZvQuSewKkLXh5-P:bqnyrvf) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/4cb323aa3b356163cb2d14deb3e7ef674b258c1d/.codeclimate.yml#L17)):*
> ```YAML
>   - "utils/graph-builder/js-yaml.min.js"
>   - "utils/graph-builder/cytoscape-cxtmenu.js"
>   - "pkg/client/petsets/"
> ```

Missing eol - minor thing...

---

*[pkg/mocks/resdefs.go, line 40 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-K_ZU4SEXIvFGtZDNlDq:-Ka7Fj6acIKgCr6p1gcc:bb6mt9b) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9920ac536e7ba4b6be65a52f49f2490f1465b338/pkg/mocks/resdefs.go#L40)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

+1
</blockquote></details>

:+1:

---

*[pkg/resources/common.go, line 137 at r3](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-Ka7H6_65PZ94qh7tqrK:-Ka7H6_65PZ94qh7tqrL:b-m7d73p) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/4cb323aa3b356163cb2d14deb3e7ef674b258c1d/pkg/resources/common.go#L137)):*
> ```Go
> 	selector, err := labels.Parse(stringSelector)
> 	if err != nil {
> 		return "error", err
> ```

Looks good, but empty string is in such situation more usual value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-:-Ka7GKddmDRjmzSdPRrS:b-do6vf8)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/163#-:-Ka7_m0_IAsMBzJ3KgLj:bnfp4nl)*

**Pull request merged**
