### PR TITLE
Implement 'on-error - ignore-all'

### PR DESCRIPTION
**Pull request by gluke77**
Partially addresses #80

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/207)

### CODE REVIEW

**Comment by nebril** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/basic_test.go, line 181 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207#-Ke3HK4yUUkYprmvss0x:-Ke3HK4yUUkYprmvss0y:bij35uy) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/15c29115e96e1fffacc8f5b7adcf40606491779f/e2e/basic_test.go#L181)):*
> ```Go
> 		Context("If failed parent is marked on-error:ignore-all", func() {
> 			It("all children including transitive must not be created", func() {
> 				parentResDef := framework.WrapWithMetaAndCreate(parentPod, map[string]interface{}{"timeout": 5, "on-error": "ignore"})
> ```

Shouldn't `ignore` be changed to `ignore-all`? Does this test test what it needs if it works with `ignore`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207)*

**Comment by gluke77** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/basic_test.go, line 181 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207#-Ke3HK4yUUkYprmvss0x:-Ke3HdQYaQJFWcb9ro4v:b-ppr4am) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/15c29115e96e1fffacc8f5b7adcf40606491779f/e2e/basic_test.go#L181)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

Shouldn't `ignore` be changed to `ignore-all`? Does this test test what it needs if it works with `ignore`?
</blockquote></details>

sure!! great catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207#-:-Ke3HkUWyCr3uqlrKiFr:bnfp4nl)*

**Comment by nebril** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207)*

**Comment by gluke77** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/basic_test.go, line 181 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207#-Ke3HK4yUUkYprmvss0x:-Ke3JpdlQY4SN9GhJ_YR:bvnrpcm) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/15c29115e96e1fffacc8f5b7adcf40606491779f/e2e/basic_test.go#L181)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

sure!! great catch
</blockquote></details>

updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207#-:-Ke3PGixhFiibbkVnm_o:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207#-:-Ke3T5-1YNIixEecCdm0:bnfp4nl)*

**Comment by nebril** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/207)*

**Pull request merged**
