### PR TITLE
PersistentVolumeClaim support

### LINKED ISSUE #135: Support for PersistentVolumeClaim object
I'd suggest that "ready" for PVC is "Bound" and not ready is "Pending" status.

### PR DESCRIPTION
**Pull request by nebril**
Also fixed a bug in which configmap keys started with configMap instead
of configmap.

fixes #135 

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/153)

### CODE REVIEW

**Comment by zefciu** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mocks/persistentvolumeclaims.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-KZ1rORtApbQxOOdU99o:-KZ1rORu9lwlra0LIfSK:b-vf159t) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/ebc796dcff56ba71de608bd5d5586096be8d3e41/mocks/persistentvolumeclaims.go#L35)):*
> ```Go
> 	pvc := &api.PersistentVolumeClaim{}
> 	pvc.Name = name
> 	switch phase {
> ```

A little confusing to use switch here, just for the sake of default value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153)*

**Comment by nebril** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mocks/persistentvolumeclaims.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-KZ1rORtApbQxOOdU99o:-KZ1tZx850Ezq6rD_EXY:bw84aaq) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/ebc796dcff56ba71de608bd5d5586096be8d3e41/mocks/persistentvolumeclaims.go#L35)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

A little confusing to use switch here, just for the sake of default value.
</blockquote></details>

What is confusing here? I cannot assign  phase var to pvc.Status.Phase directly because it's not string, but string subtype. I could use either ifs or switch here, decided switch will be more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153)*

**Comment by gluke77** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[scheduler/scheduler_test.go, line 333 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-KZ5opVmjUj2EaJlucFw:-KZ5opVnLSP331QwSzx3:blmkpl0) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/f7181d8df2b4f7d45d85862a0d741810866292b6/scheduler/scheduler_test.go#L333)):*
> ```Go
> 		keys := ""
> 		for key := range depGraph {
> 			keys = keys + ", " + key
> ```

You gonna get leading ", " here. And adding strings in a loop is a kinda bad taste. Pls consider

ks := make([]string, 0, len(depGraph)
for key := range depGraph {
    ks = append(ks, key)
}
keys = strings.Join(ks, ", ")

 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153)*

**Comment by zefciu** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[mocks/persistentvolumeclaims.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-KZ1rORtApbQxOOdU99o:-KZ5x2Tuqjz_KNbr1jEt:b-2i668v) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/ebc796dcff56ba71de608bd5d5586096be8d3e41/mocks/persistentvolumeclaims.go#L35)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

What is confusing here? I cannot assign  phase var to pvc.Status.Phase directly because it's not string, but string subtype. I could use either ifs or switch here, decided switch will be more readable.
</blockquote></details>

But if you can construct phase from string, then only one if would be necessary. If you think this is more clear, then OK, but I don't like it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153)*

**Comment by nebril** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[mocks/persistentvolumeclaims.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-KZ1rORtApbQxOOdU99o:-KZ5y5HDe1grb2Eo7djF:b-i11uit) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/ebc796dcff56ba71de608bd5d5586096be8d3e41/mocks/persistentvolumeclaims.go#L35)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

But if you can construct phase from string, then only one if would be necessary. If you think this is more clear, then OK, but I don't like it.
</blockquote></details>

Please give me an example of how would you do it, I don't understand your remarks.

---

*[scheduler/scheduler_test.go, line 333 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-KZ5opVmjUj2EaJlucFw:-KZ5yBP2i7XrLhTXWJH5:b-bo8bhh) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/f7181d8df2b4f7d45d85862a0d741810866292b6/scheduler/scheduler_test.go#L333)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

You gonna get leading ", " here. And adding strings in a loop is a kinda bad taste. Pls consider

ks := make([]string, 0, len(depGraph)
for key := range depGraph {
    ks = append(ks, key)
}
keys = strings.Join(ks, ", ")

 
</blockquote></details>

Yeah, it's kinda messy leftover from when I was trying to fix this test. You are 100% right, will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-:-KZ651u-aB5_1TRuuqWB:bnfp4nl)*

**Comment by zefciu** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[mocks/persistentvolumeclaims.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-KZ1rORtApbQxOOdU99o:-KZ7By_l3yef5LKxj79l:b-j978hh) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/ebc796dcff56ba71de608bd5d5586096be8d3e41/mocks/persistentvolumeclaims.go#L35)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

Please give me an example of how would you do it, I don't understand your remarks.
</blockquote></details>

After discussion OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153)*

**Comment by zefciu** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/153#-:-KZ7C5qQ8K9FclWlem75:bnfp4nl)*

**Pull request merged**
