### PR TITLE
[wip] Other start

### PR DESCRIPTION
**Pull request by pigmej**
Runit integration etc.

AC can be started by exec into container and then controlled using /etc/sv/ac/supervise/control PIPE

### CODE REVIEW

**Comment by nhlfr** [comment]
Any reason why we use runit in Docker instead of making just "flat" containers (it means, running one entrypoint application)?

**Comment by nebril** [comment]
@nhlfr because deleting pods is tedious and it's easier to run exec on the. We should have API in the container set up in the future.

**Comment by pigmej** [comment]
@nhlfr as @nebril mentioned, we need some API, it will need to persist (as other "controllers").

And yes this `exec` solution is hacky, but it's better than nothing ;-)

**Comment by nhlfr** [comment]
OK, got it, thx for explanation.

**Pull request merged**
