### PR TITLE
Use channel to terminate deployment workflow

### PR DESCRIPTION
**Pull request by dshulyak**
Use channel to terminate deployment workflow

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/211)

### CODE REVIEW

**Comment by jellonek** [comment]
Looks ok, with one small question.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/deploy.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-KebzydxM5napmHvm_a7:-KebzydxM5napmHvm_a8:bhaej2p) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/cmd/deploy.go#L87)):*
> ```Go
> 		log.Println("No cycles detected.")
> 	}
> 	stopChan := make(chan struct{})
> ```

Wouldn't be better to use `chan error` in all places instead of `chan struct{}`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-:-Kec-r0WW1wCuf-Y5yrS:bmvujb0)*

**Comment by dshulyak** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/deploy.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-KebzydxM5napmHvm_a7:-Kec1K0diZ3CmdiYHOOz:bva4lr8) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/cmd/deploy.go#L87)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Wouldn't be better to use `chan error` in all places instead of `chan struct{}`?
</blockquote></details>

afaik it is common in go development to use chan struct{} for termination, cause it clearly shows that we are not interested in value. Also it is slightly more efficient :) struct{} always will take 0 bytes, but error will take number of bytes allocated to empty interface thus:
```
package main

import "fmt"
import "unsafe"

func main() {
	stopE := make(chan error)
	close(stopE)
	stopS := make(chan struct{})
	close(stopS)
	fmt.Println(unsafe.Sizeof(<-stopE)) // 16
	fmt.Println(unsafe.Sizeof(<-stopS)) // 0
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/deploy.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-KebzydxM5napmHvm_a7:-Kec4oWvPV2MUMYBUmJh:b8bnokh) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/cmd/deploy.go#L87)):*
<details><summary><i>Previously, dshulyak (Dmitry Shulyak) wrote…</i></summary><blockquote>

afaik it is common in go development to use chan struct{} for termination, cause it clearly shows that we are not interested in value. Also it is slightly more efficient :) struct{} always will take 0 bytes, but error will take number of bytes allocated to empty interface thus:
```
package main

import "fmt"
import "unsafe"

func main() {
	stopE := make(chan error)
	close(stopE)
	stopS := make(chan struct{})
	close(stopS)
	fmt.Println(unsafe.Sizeof(<-stopE)) // 16
	fmt.Println(unsafe.Sizeof(<-stopS)) // 0
}
```

</blockquote></details>

This looks like channel for error passing, which is also used as a termination method. Also even it if's a bit more optimal in memory usage it's not clear from start what types of structs can be passed there. IMO readability count, more than efficiency there.
Don't give me wrong - this works and I have no strong opinion on that. If someone else will accept this - you have my LGTM ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211)*

**Comment by nebril** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/scheduler/scheduler.go, line 121 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-Kec5xrLA5MZI9-YTn4X:-Kec5xrMjPTDmb0U6wRR:b-trl7cq) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/pkg/scheduler/scheduler.go#L121)):*
> ```Go
> }
> 
> func statusWaiter(sr *ScheduledResource, ch chan error) bool {
> ```

I don't like the name of this function. It suggests that some kind of waiter is returned, but it's just a bool function. What about `isResourceFinished` or sth like that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211)*

**Comment by nebril** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/deploy.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-KebzydxM5napmHvm_a7:-Kec7_2ElthpSE3Dx4uP:b-7p73ia) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/cmd/deploy.go#L87)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This looks like channel for error passing, which is also used as a termination method. Also even it if's a bit more optimal in memory usage it's not clear from start what types of structs can be passed there. IMO readability count, more than efficiency there.
Don't give me wrong - this works and I have no strong opinion on that. If someone else will accept this - you have my LGTM ;)
</blockquote></details>

@jell for me it seems like this channel is not for error passing, it's just for signalling that the deployment timeout is reached.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/deploy.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-KebzydxM5napmHvm_a7:-Kec9qH3mG--724JCLeB:bh2hmz0) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/cmd/deploy.go#L87)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary><blockquote>

@jell for me it seems like this channel is not for error passing, it's just for signalling that the deployment timeout is reached.
</blockquote></details>

... by sending `nil`, or thing which only supports `error` interface ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211)*

**Comment by dshulyak** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/deploy.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-KebzydxM5napmHvm_a7:-KecCGLQKIaFxVsvBY0M:b-5m8zmo) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/cmd/deploy.go#L87)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

... by sending `nil`, or thing which only supports `error` interface ;)
</blockquote></details>

nothing should be sent to this channel, the intent to use it only with close

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/deploy.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-KebzydxM5napmHvm_a7:-KecDuUQVnJJ5AGLk2UX:b2nhysk) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/6d38f3986a76ae9c9bd5adcad1d4e1100622e0da/cmd/deploy.go#L87)):*
<details><summary><i>Previously, dshulyak (Dmitry Shulyak) wrote…</i></summary><blockquote>

nothing should be sent to this channel, the intent to use it only with close
</blockquote></details>

ack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-:-KedIllMTUpCLPbyotTe:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/211#-:-KedM-O5XnSfhmH0CYdA:bnfp4nl)*

**Pull request merged**
