### PR TITLE
Initial support for ConfigMaps

### LINKED ISSUE #109: ConfigMap support
Support for ConfigMap object

### PR DESCRIPTION
**Pull request by pigmej**
Closes #109

This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/107)

### CODE REVIEW

**Comment by nebril** [comment]
Please add mocks, tests and add this new type to TestGraphAllResourceTypes in scheduler_test.go

**Comment by pigmej** [comment]
@nebril I know ;) I even added `do not merge yet` label :)

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/107#-:-KXPpnHQxRHaMZ19_G6k:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: 9 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/107#-:-KXQ9YdfgEzqmnVyKXn9:bnfp4nl)*

**Comment by gluke77** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/107#-:-KXeUqQS_O6hEbcWScs5:bnfp4nl)*

**Pull request merged**
