### PR TITLE
Ability to parametrize resource key in dependency

### PR DESCRIPTION
**Pull request by istalker2**
Currently, flow resource name is auto-generated from replica name of the
outer (consuming) graph and dependency name, whose child is the flow
resource. As a result, if we want a flow call to depend on two parent
resources, we will get two flow calls after each parent becomes ready,
rather than one call after both turn ready.

If we make flow name generation depend on replica name only, the problem
above will be solved, however it will still not be possible to have one
flow call for entire graph rather than for each replica. Also in some
cases we might want it to be called for each dependency, if there are
different arguments passed along each of them.

If we remove name generation at all, the only way, how we'll be able to
achieve behavior other, than one call per graph will be to make the
flow name by dynamic, i.e. include things like $AC_NAME or $arg1.
Though technically it solves the problem, it has its own major cons:
* Names of the flows will become ugly and flow name is a user facing
  thing because it will propagate into CLI commandlines
* Flows were supposed to be reusable. Flow author might not know
  how it will be used and not include needed variable in flow name
* Even if he did, one flow may still be used in different ways.
  For example, what if the flow name is "flow-$AC_NAME" and I want
  to call it just once for all replicas of my flow. There is no way
  to pass $AC_NAME explicitly to the flow to make it be a fixed value.

This commit proposes another solution to the problem. There is no need
to use variables in flow names. Instead, it can be parametrized on the
caller side with new dependency syntax. Now I can add optional suffix
(3rd component of the name) to parent/child names in dependencies.
For example: `child: flow/my-flow/$AC_NAME`

Resource definition is looked up by first 2 components (flow/my-flow),
but resources from different replicas are merged only if the whole
3-component key is the same.

So we get:
* Ability to call flows by simple names
* It is now possible to call flow several times within another flow.
  Without this change it is impossible, because node names are unique
  in the graph and if we include several flow calls, we will get cycle
  in the graph. However, with this change node identity is identified
  by 3-part string, while resource definition by just two, so we can
  have several usage of the same resource that differ by 3-rd component
  only
* Similar to flows, it becomes possible to include the same resource
  more than once in a graph. For example it will become possible to
  create resource, do something and then update the same resource. Or
  delete it.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/259)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/client/flows.go, line 168 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/259#-KkPi2uWIUVe8b8nzZeI:-KkPi2uX1DYnFb9opNFi:buhon96) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/589d1df76e6c86348f5302c9e10b4e98e49322b1/pkg/client/flows.go#L168)):*
> ```Go
> 
> func (r *replicas) Update(replica *Replica) error {
> 	//result := &Replica{}
> ```

Commented code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/259)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/259#-:-KkPnsCDkvnCoYyoN2F5:bnfp4nl)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/259#-:-Km6K0_U_1o3ZDrBNwAJ:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/259#-:-Km6yDyhW3GT8qGWnL0H:bnfp4nl)*

**Pull request merged**
