### PR TITLE
Rename resource interfaces to better reflect their meaning

### PR DESCRIPTION
**Pull request by gluke77**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/146)

### CODE REVIEW

**Comment by zefciu** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[interfaces/interfaces.go, line 21 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146#-KYnBACJjNffFB-evBQQ:-KYnBACJjNffFB-evBQR:b-rdo5qw) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9974925f3b12d4899b52c916f98523ef7b468de8/interfaces/interfaces.go#L21)):*
> ```Go
> )
> 
> //Resource is an interface for AppController supported resources
> ```

Update the docstring

---

*[interfaces/interfaces.go, line 39 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146#-KYnBDUjugbRmD14OTRq:-KYnBDUjugbRmD14OTRr:b-89a4l7) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9974925f3b12d4899b52c916f98523ef7b468de8/interfaces/interfaces.go#L39)):*
> ```Go
> }
> 
> // Reporter is an interface that implements getting dependency reports
> ```

Ditto

---

*[report/report.go, line 18 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146#-KYnBK0P-IcN6IpfOVka:-KYnBK0QLShS5zpW5Cvg:b-9r3ids) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/944fd8ab34e5c874487303e77cfec2ae8bcf5021/report/report.go#L18)):*
> ```Go
> type DeploymentReport []NodeReport
> 
> // SimpleReporter creates report for simple binary cases
> ```

Shouldn't this name be also updated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146)*

**Comment by gluke77** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[interfaces/interfaces.go, line 21 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146#-KYnBACJjNffFB-evBQQ:-KYnCOk66P7NeRh4n7eY:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9974925f3b12d4899b52c916f98523ef7b468de8/interfaces/interfaces.go#L21)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

Update the docstring
</blockquote></details>

Done.

---

*[interfaces/interfaces.go, line 39 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146#-KYnBDUjugbRmD14OTRq:-KYnCO2p-yhd5pJDILWd:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/9974925f3b12d4899b52c916f98523ef7b468de8/interfaces/interfaces.go#L39)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

---

*[report/report.go, line 18 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146#-KYnBK0P-IcN6IpfOVka:-KYnC1E9qNenXUm2nKt4:b-kcjqjy) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/944fd8ab34e5c874487303e77cfec2ae8bcf5021/report/report.go#L18)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary><blockquote>

Shouldn't this name be also updated?
</blockquote></details>

I guess, here 'Reporter' is fine, because it more or less reflects what it does, SimpleReportingResource would be too long

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146)*

**Comment by jellonek** [comment]
Reviewed 16 of 16 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146#-:-KYnI3BcpoeG4BoFBMn8:bnfp4nl)*

**Comment by zefciu** [comment]
Reviewed 15 of 16 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/146)*

**Comment by zefciu** [comment]
:lgtm:

**Pull request merged**
