### PR TITLE
Add 'on-error' subgraph

### PR DESCRIPTION
**Pull request by gluke77**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/184)

### CODE REVIEW

**Comment by pigmej** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/scheduler/scheduler.go, line 116 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-KbP10Mou8ZgEvTRP2es:-KbP10Mou8ZgEvTRP2et:bvvq4yi) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/92d63ba3814e95a49b8a81cf4499264901053646/pkg/scheduler/scheduler.go#L116)):*
> ```Go
> func (sr *ScheduledResource) Wait(checkInterval time.Duration) error {
> 	for {
> 		time.Sleep(checkInterval)
> ```

can't we first check and then wait? In average case it will be the same, but for some cases it will be faster, isn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184)*

**Comment by gluke77** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/scheduler/scheduler.go, line 116 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-KbP10Mou8ZgEvTRP2es:-KbPDSkgediTo8xcSSFU:b-d7bhn0) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/92d63ba3814e95a49b8a81cf4499264901053646/pkg/scheduler/scheduler.go#L116)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

can't we first check and then wait? In average case it will be the same, but for some cases it will be faster, isn't it?
</blockquote></details>

will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-:-KbiikvoHKnsjXcPPWN2:bnfp4nl)*

**Comment by jellonek** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/scheduler/scheduler.go, line 116 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-KbP10Mou8ZgEvTRP2es:-KbiiqH0FZqgMXwMW1cm:blx9hg) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/92d63ba3814e95a49b8a81cf4499264901053646/pkg/scheduler/scheduler.go#L116)):*
<details><summary><i>Previously, gluke77 (Illia Khudoshyn) wrote…</i></summary><blockquote>

will do
</blockquote></details>

Exported func comment should start from this func name. https://blog.golang.org/godoc-documenting-go-code
Should probably not pass by linter, but we have this disabled because of our beginnings. Almost all new code afair is consistent with this rule.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184)*

**Comment by nebril** [comment]
Can you add an example deployment that would demonstrate how to use this feature?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-:-Kbit5xs39wF5-F74W6f:b-q6sdhu)*

**Comment by gluke77** [comment]
Added example

---

Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-:-KbjUph3_4EIVwVHgkG_:blls6kl)*

**Comment by gluke77** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/scheduler/scheduler.go, line 116 at r1](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-KbP10Mou8ZgEvTRP2es:-KbnzO4SvF89J7zcFAwV:bio25sm) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/92d63ba3814e95a49b8a81cf4499264901053646/pkg/scheduler/scheduler.go#L116)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Exported func comment should start from this func name. https://blog.golang.org/godoc-documenting-go-code
Should probably not pass by linter, but we have this disabled because of our beginnings. Almost all new code afair is consistent with this rule.
</blockquote></details>

It does. Or I didn't get your point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184)*

**Comment by nebril** [comment]
lgmt overall. Does the extended example work fine with that change?

---

Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-:-KboKw1jc2CFHWAUemnk:bpgzcp8)*

**Comment by gluke77** [comment]
yep it does after rebasing against fresh master with recent fix

---

Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-:-Kbp--JTEhyJoUH4R2eM:b-6lk32z)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-:-Kbp-jAnDSKagbLBnyq4:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/184#-:-KbtyXits9sXIDdDqgRU:bnfp4nl)*

**Pull request merged**
