### PR TITLE
Use more standard directories.

### PR DESCRIPTION
**Pull request by jellonek**
Other possibility would be to use `/usr/share/kubeac`, but `/opt` seems also ok for things distributed in binary form.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/60)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 9 \[r1\]](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60#-KQKNu7IaJz_gf_-OTV8:-KQKNu7IaJz_gf_-OTV9:b-31mel0) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/55253ed529da1abe9cdf38b38746597ec4494849/Dockerfile#L9)):*
> ```Dockerfile
> 
> RUN apk --no-cache add git
> RUN go get ./... && go build -o kubeac cmd/kubeac/main.go && go build -o wrap cmd/wrap/main.go && go build -o bootstrap cmd/bootstrap/main.go && mv kubeac /usr/bin/kubeac && mv wrap /usr/bin/wrap && mv bootstrap /usr/bin/bootstrap && mv /go/src/github.com/Mirantis/k8s-AppController/manifests /opt/kubeac/manifests && rm -fr /go
> ```

Shouldn't you create /opt/kubeac first ? I'm pretty sure that it will crash with "No such file or directory"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60)*

**Comment by pigmej** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 9 \[r1\]](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60#-KQKNu7IaJz_gf_-OTV8:-KQKT3tZE7dLlO8LK4l5:b-ofvt4n) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/55253ed529da1abe9cdf38b38746597ec4494849/Dockerfile#L9)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary>
> Shouldn't you create /opt/kubeac first ? I'm pretty sure that it will crash with "No such file or directory"
</details>
https://hub.docker.com/r/mirantis/k8s-appcontroller/builds/bjjlk2jnm84oqvnzdbwnd5b/ confirms it with`can't rename '/go/src/github.com/Mirantis/k8s-AppController/manifests': No such file or directory` 

Please fix @jellonek 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 9 \[r1\]](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60#-KQKNu7IaJz_gf_-OTV8:-KQKTIRU9b2gLdW88x-L:b-896fix) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/55253ed529da1abe9cdf38b38746597ec4494849/Dockerfile#L9)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary>
> https://hub.docker.com/r/mirantis/k8s-appcontroller/builds/bjjlk2jnm84oqvnzdbwnd5b/ confirms it with`can't rename '/go/src/github.com/Mirantis/k8s-AppController/manifests': No such file or directory` 
> 
> Please fix @jellonek 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60)*

**Comment by nebril** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/60#-:-KQKUBCCT2DPRIBz0nU2:bnfp4nl)*

**Pull request merged**
