### PR TITLE
Use examples as separate e2e test suite

### PR DESCRIPTION
**Pull request by dshulyak**
This PR allows to run examples described in yaml files as a part of e2e suite.
Each example should be specified in examples_test.go as a different ginkgo test, including all possible conditions, for example extended test can not be run on kube of version 1.4.

Added new runner (ExamplesFramework) that adds couple of useful utilities for running examples:
- reads all yaml files in specified directory, and creates objects from them
- verifies deployment status using appcontroller library

e2e binary now supports 2 additional arguments:
- `--examples-directory` base directory for all examples
- `--k8s-version` kubernetes version that is used for e2e tests

This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/203)

### CODE REVIEW

**Comment by dshulyak** [comment]
Thinking about using create.sh in each example for creation..

**Comment by nebril** [comment]
Maybe instead of using create.sh create a common create.sh for all examples with yaml file conventions?
```
for x in *resource.yaml; do
  cat $x | (...);
done
```

**Comment by dshulyak** [comment]
I think i will stick to parser in e2e tests for a while, and maybe change it later.

**Comment by nebril** [comment]
Awesome. One typo in file name, otherwise lgtm.

---

Reviewed 7 of 7 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[e2e/example_runnner.go, line 1 at r2](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/203#-Kdekyb79iMGXy2CVW5R:-Kdekyb79iMGXy2CVW5S:b-bej4on) ([raw file](https://github.com/mirantis/k8s-appcontroller/blob/ce5caf8bbad584edca2eb03b190df6fbac7ef0ad/e2e/example_runnner.go#L1)):*
> ```Go
> // Copyright 2017 Mirantis
> ```

This file name has on `n` too many :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/203#-:-Kdeogy3jjq3lwPcGbDG:bj183lg)*

**Comment by nebril** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/203#-:-KdfKeViRpbhfJW-wQvd:bnfp4nl)*

**Comment by gluke77** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/203#-:-KdgSA9o2I8VcLJtiQxY:bnfp4nl)*

**Comment by gluke77** [comment]
we should not merge it before travis get fixed thou

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/203#-:-KdgSnpTOkjb_BnUAb-H:bjj078y)*

**Pull request merged**
