### PR TITLE
PetSet support

### PR DESCRIPTION
**Pull request by nebril**
Extended client, scheduler, resources modules to support PetSets

Added test for creating dependency graph with all supported resources

Added PetSet mocks

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/k8s-appcontroller/68)

### CODE REVIEW

**Comment by nebril** [comment]
Tested manually on updated extended example, seems to be working fine.

**Comment by nebril** [comment]
fixes #64

**Comment by gluke77** [comment]
LGTM

**Comment by pigmej** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/k8s-appcontroller/68)*

**Pull request merged**
